# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 6) do

  create_table "activities", :force => true do |t|
    t.column "workout_id",  :integer
    t.column "exercise_id", :integer
    t.column "resistance",  :integer
    t.column "repetitions", :integer
  end

  create_table "exercises", :force => true do |t|
    t.column "name",    :string
    t.column "user_id", :integer
  end

  create_table "goals", :force => true do |t|
    t.column "name",    :string
    t.column "value",   :decimal
    t.column "last",    :decimal
    t.column "user_id", :integer
  end

  create_table "results", :force => true do |t|
    t.column "goal_id", :integer
    t.column "date",    :date
    t.column "value",   :decimal
  end

  create_table "users", :force => true do |t|
    t.column "login",                     :string
    t.column "email",                     :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
  end

  create_table "workouts", :force => true do |t|
    t.column "date",    :date
    t.column "label",   :string
    t.column "user_id", :integer
  end

end
