# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 4) do

  create_table "blogs", :force => true do |t|
    t.column "name", :string
  end

  create_table "categories", :force => true do |t|
    t.column "name", :string
  end

  create_table "categories_posts", :id => false, :force => true do |t|
    t.column "category_id", :integer
    t.column "post_id",     :integer
  end

  create_table "images", :force => true do |t|
    t.column "name",       :string
    t.column "extension",  :string
    t.column "created_at", :datetime
  end

  create_table "posts", :force => true do |t|
    t.column "blog_id",    :integer
    t.column "title",      :string
    t.column "body",       :text
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

end
