# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 7) do

  create_table "avatars", :force => true do |t|
    t.column "user_id",      :integer
    t.column "content_type", :string
    t.column "filename",     :string
    t.column "size",         :integer
    t.column "width",        :integer
    t.column "height",       :integer
    t.column "created_at",   :datetime
    t.column "parent_id",    :integer
    t.column "thumbnail",    :string
  end

  create_table "comments", :force => true do |t|
    t.column "title",            :string,   :limit => 50, :default => ""
    t.column "comment",          :string,                 :default => ""
    t.column "created_at",       :datetime,                               :null => false
    t.column "commentable_id",   :integer,                :default => 0,  :null => false
    t.column "commentable_type", :string,   :limit => 15, :default => "", :null => false
    t.column "user_id",          :integer,                :default => 0,  :null => false
  end

  add_index "comments", ["user_id"], :name => "fk_comments_user"

  create_table "details", :force => true do |t|
    t.column "user_id",      :integer
    t.column "headline",     :string
    t.column "about_me",     :text
    t.column "like_to_meet", :text
    t.column "interests",    :text
    t.column "music",        :text
    t.column "movies",       :text
    t.column "television",   :text
    t.column "books",        :text
  end

  create_table "galleries", :force => true do |t|
    t.column "user_id",      :integer
    t.column "name",         :string
    t.column "description",  :text
    t.column "created_at",   :datetime
    t.column "photos_count", :integer,  :default => 0
    t.column "privacy",      :boolean
  end

  create_table "photos", :force => true do |t|
    t.column "user_id",      :integer
    t.column "gallery_id",   :integer
    t.column "parent_id",    :integer
    t.column "content_type", :string
    t.column "filename",     :string
    t.column "thumbnail",    :string
    t.column "size",         :integer
    t.column "width",        :integer
    t.column "height",       :integer
    t.column "created_at",   :datetime
    t.column "description",  :string
  end

  create_table "posts", :force => true do |t|
    t.column "user_id",    :integer
    t.column "headline",   :string
    t.column "body",       :text
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "users", :force => true do |t|
    t.column "login",                     :string
    t.column "email",                     :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
    t.column "first_name",                :string
    t.column "last_name",                 :string
    t.column "gender",                    :string
    t.column "birthday",                  :date
    t.column "street",                    :string
    t.column "city",                      :string
    t.column "state",                     :string
    t.column "zip",                       :string
  end

end
